name: Publish

on:
  workflow_run:
    workflows: ["ReleaseStart"]
    types:
      - completed

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
        with:
          ref: release
      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 11
      - name: Release build
        # assembleRelease for all modules, excluding non-library modules: samples, docs
        run: ./gradlew assembleRelease -x :stream-chat-android-ui-components-sample:assembleRelease -x :stream-chat-android-compose-sample:assembleRelease -x :stream-chat-android-docs:assembleRelease
      - name: Source jar and dokka
        run: ./gradlew androidSourcesJar javadocJar

      - name: Set up Nexus credentials
        env:
          NEXUS_USERNAME: ${{secrets.NEXUS_USERNAME}}
          NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}
        run: |
          echo "nexusUsername=$NEXUS_USERNAME" 1>>local.properties
          echo "nexusPassword=$NEXUS_PASSWORD" 1>>local.properties

      - name: Publish to Nexus
        run: ./gradlew publish
