name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
        with:
          ref: release

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Nexus credentials
        env:
          NEXUS_USERNAME: ${{secrets.NEXUS_USERNAME}}
          NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}
        run: |
          echo "nexusUsername=$NEXUS_USERNAME" 1>>local.properties
          echo "nexusPassword=$NEXUS_PASSWORD" 1>>local.properties

      - name: Publish to Nexus
        run: ./gradlew publishReleasePublicationToNexusRepository
